# Generated by Django 5.1.6 on 2025-03-01 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(verbose_name='Image URL')),
                ('alt', models.CharField(max_length=255, verbose_name='Alt Text')),
                ('width', models.PositiveIntegerField(verbose_name='Width')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('data_file_width', models.PositiveIntegerField(verbose_name='Data File Width')),
                ('data_file_height', models.PositiveIntegerField(verbose_name='Data File Height')),
            ],
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Number')),
                ('atk_def', models.CharField(max_length=50, verbose_name='ATK/DEF')),
                ('card_type', models.CharField(max_length=50, verbose_name='Type')),
                ('rarity', models.CharField(max_length=10, verbose_name='Rarity')),
                ('lore', models.TextField(verbose_name='Lore')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=255, verbose_name='Japanese')),
                ('romaaji', models.CharField(max_length=255, verbose_name='Rōmaji')),
                ('translated', models.CharField(max_length=255, verbose_name='Translated')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=255, verbose_name='Card Name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='dm1.cardimage'),
        ),
        migrations.AlterField(
            model_name='card',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='dm1.cardinfo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='languages',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='dm1.language'),
        ),
    ]
