# Generated by Django 5.1.6 on 2025-03-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm1', '0002_cardimage_cardinfo_language_alter_card_card_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='info',
        ),
        migrations.RemoveField(
            model_name='card',
            name='languages',
        ),
        migrations.AddField(
            model_name='cardimage',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_image', to='dm1.card'),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_info', to='dm1.card'),
        ),
        migrations.AddField(
            model_name='language',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='dm1.card'),
        ),
    ]
